
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: marketgo_db
        - name: MYSQL_USER
          value: marketgo_user
        - name: MYSQL_PASSWORD
          value: marketgo_pass
        ports:
        - containerPort: 3306
